"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var stats_tracker_1 = require("./stats-tracker");
var test_1 = require("./test");
var tracker = stats_tracker_1.StatsTracker.instance;
tracker.widgetViews = 90;
tracker.buttonClicks = 64;
tracker.facebookShares = 20;
tracker.twitterShares = 30;
console.log("Widget Views:".concat(tracker.widgetViews));
console.log("Button clicks:".concat(tracker.buttonClicks));
console.log("Facebook Shares:".concat(tracker.facebookShares));
console.log("Twitter Shares:".concat(tracker.twitterShares));
tracker.widgetViews++;
tracker.twitterShares += 2;
(0, test_1.test)();
